// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD1EjJqDwynmA42UHftp_m5XRSIJcKwpY',
    appId: '1:743137596045:android:3c121ccc3148dd41e088c4',
    messagingSenderId: '743137596045',
    projectId: 'air-talks',
    storageBucket: 'air-talks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw0sNhrra7JnDIuYwScSIhCvg98lATYtE',
    appId: '1:743137596045:ios:dd62faf428498efce088c4',
    messagingSenderId: '743137596045',
    projectId: 'air-talks',
    storageBucket: 'air-talks.appspot.com',
    androidClientId: '743137596045-6m5oh541ebpqpdcklqfln2n1l4qv8suh.apps.googleusercontent.com',
    iosClientId: '743137596045-fr07bu8unuucq4c1bcmvqp8mdmt8263c.apps.googleusercontent.com',
    iosBundleId: 'com.example.airTalks',
  );
}
